Libraries-NumPy & Pandas Assignment

Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.

In [7]:
import pandas as pd

# load dataset
df = pd.read_csv("retail_dataset .csv")

# first 5 rows
df.head()

# dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.

In [11]:
# missing values count in each column
df.isnull().sum()

# total missing values
df.isnull().sum().sum()

12

Q3. Replace missing values in the Quantity and Price columns with their respective mean values using
Pandas.

In [16]:
# fill missing Quantity with mean
df["Quantity"].fillna(df["Quantity"].mean(), inplace=True)

# fill missing Price with mean
df["Price"].fillna(df["Price"].mean(), inplace=True)
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

Q4. Remove all rows where the Product Category or Region column contains missing values.

In [26]:
# drop rows where Product Category or Region is missing
df.dropna(subset=["Product Category", "Region"], inplace=True)
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

Q5. Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.

In [19]:
# create new column Revenue
df["Revenue"] = df["Quantity"] * df["Price"]

# check updated data
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.

In [20]:
# total revenue of all data
df["Revenue"].sum()

465529.66058002145

Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.

In [21]:
# total revenue per category
df.groupby("Product Category")["Revenue"].sum()

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue.

In [24]:
# group data
rev_cat = df.groupby("Product Category")["Revenue"].sum()

# top 3 categories
rev_cat.sort_values(ascending=False).head(3)

# bottom 3 categories
rev_cat.sort_values().head(3)

Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue.

In [29]:
# revenue per region
rev_region = df.groupby("Region")["Revenue"].sum()

# highest revenue region
rev_region.idxmax()

# lowest revenue region
rev_region.idxmin()

'West'

Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.

In [40]:
# convert date (fix applied)
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# create Month-Year
df["Month_Year"] = df["Date"].dt.strftime("%Y-%m")

# ensure revenue exists
df["Revenue"] = df["Quantity"] * df["Price"]

# monthly revenue
df.groupby("Month_Year")["Revenue"].agg(['sum','mean','median','std'])

                     sum          mean        median           std
Month_Year
2023-01     24226.000000   6056.500000   5632.000000   5403.780498
2023-02      5017.000000   1672.333333   1496.000000    610.894699
2023-03      4184.000000   2092.000000   2092.000000   1199.253101
2023-04     37089.526316   7417.905263   9310.000000   3893.541831
2023-06      1089.000000   1089.000000   1089.000000           NaN
2023-07     14532.210526   7266.105263   7266.105263    992.629056
2023-08     67718.000000   6156.181818   4501.000000   7782.437765
2023-09      8511.000000   4255.500000   4255.500000   5207.841443
2023-10     11448.000000  11448.000000  11448.000000           NaN
2023-11      6492.000000   3246.000000   3246.000000    432.749350
2023-12      1609.000000    804.500000    804.500000    734.683946
2024-01     19768.000000   3294.666667   3237.000000   1447.680858
2024-02     28011.000000   5602.200000   4991.000000   4631.316465
2024-03      6373.000000   3186.500000   3186.500000   1386.636398
2024-04     20209.000000   4041.800000   1971.000000   4000.794259
2024-05     27915.000000   5583.000000   4704.000000   2565.478026
2024-06     27101.000000   9033.666667   8085.000000   4109.951987
2024-07     33319.081633   3331.908163   2524.469388   2961.400416
2024-08      9240.000000   9240.000000   9240.000000           NaN
2024-09     22208.105263   3701.350877   3621.052632   1647.239816
2024-10     26569.000000   4428.166667   2730.000000   4160.052616
2024-11     21170.736842   2646.342105   1842.000000   2656.332271
2024-12     41730.000000  13910.000000   8660.000000  11254.283629